name: Test and lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  linting:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --group test

      - name: Lint implementation
        run: flake8
